### ISSUE TITLE
validate_token function

### ISSUE THREAD

**Issue by ferhimedamine** [fillipvt/with-graphql-faunadb-cookie-auth#1]
@fillipvt great repo 👍 .. could you add the validate_token function in the documentation or share the the code within this ticket. Many thanks in advance 🙏

**Comment by fillipvt** [comment]
hey @ferhimedamine 
I guess you found the func definition
but just in case, [here it is](https://github.com/fillipvt/with-graphql-faunadb-cookie-auth/blob/master/lib/fauna/exampleFunctions.js#L44)

**Comment by ferhimedamine** [comment]
@fillipvt indeed found it , you code worked like a charm.
![image](https://user-images.githubusercontent.com/7574816/83953245-05af4500-a83f-11ea-9cec-d5fd55240f82.png)
👍
